### PR TITLE
Get IK running

### PR DESCRIPTION
**Pull request by Berk-Tosun**
Small changes to get it running with:

* python: 3.9
* pinocchio: 2.6
* numpy: 1.23
* pybullet: 3.21

Also formatted by black.

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on the main branch.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

**Comment by nim65s** [comment]
Hi, 
Thanks for this update, but this is really hard to review something with a reformat and changes. Could make separate requests for those your update and the reformat ? or at least 2 commits ?

**Comment by Berk-Tosun** [comment]
Hi,

That is a valid request, of course. I am on a tight schedule at the moment. I will open another PR with proper commits in a couple weeks time.

I can also fix the ID.

**Comment by nim65s** [comment]
Ok, I can help a bit, then.

**Comment by nim65s** [comment]
Format is OK on the devel branch now. You can apply the change you need when you want.

**Pull request closed without merging**
